### ISSUE TITLE
`get_all_custom_field_meta` saves data as strings even if ACF returns it as an int.

### ISSUE THREAD

**Issue by justlevine** [timothyjensen/acf-field-group-values#6]
All array data from `get_all_custom_field_meta()` are saved as strings, even if ACF declares it as an int.

Eg: 
1. Create field `acf_number_test`, type = `Number`.
2. `$acf_page = get_all_custom_field_meta( get_the_id(), $config`.
3.  `$math_equation = ($acf_page['acf_number_test'] / 5)` //Warning: A non-numeric value encountered

**Comment by timothyjensen** [comment]
Yes, this is expected behavior because WordPress stores all post meta as a string.  ACF does extra processing to convert meta values to different formats (such as a post object), but the values themselves are actually strings. 

For the example you provided, I highly suggest checking the meta values before using them in an equation. You should do this even when using ACF for retrieving post meta.

```php
$value = null;

if ( is_numeric( $acf_page['acf_number_test']  ) ) {
    $value = floatval( $acf_page['acf_number_test'] );
}

if ( isset( value ) ) {
    $math_equation = ( $value / 5 );
}
```

**Comment by justlevine** [comment]
Crap, ditto for images, and a bunch of other fields.

Both your blog post, and the readme.md here made it seem like this is a drop-in replacement for get_fields().

Might I suggest clarifying that this function only returns string values, and doesnt process them according to the return types set in ACF?
